---
title: "Seek and you may (not) find: A multi-institutional analysis of where research data are shared"
date: 2024-04-25
author:
  - name: Lisa R. Johnson
    url: 
    orcid: 0000-0001-6908-9240
    affiliation: University of Wisconsin
  - name: Alicia Hofelich Mohr
    orcid: 0000-0002-7644-4105
    url: 
    affiliation: University of Minnesota
  - name: Joel Herndon
    url: https://joelherndon.info
    orcid: 0000-0001-9995-9040
    affiliation: Duke University
  - name: Shawna Taylor
    url: 
    orcid: 0000-0002-9842-7867
    affiliation: Johns Hopkins University
  - name: Shawna Taylor
    url: 
    orcid: 0000-0002-9842-7867
    affiliation: Johns Hopkins University
  - name: Jake Carlson
    url: 
    orcid: 0000-0003-2733-0969
    affiliation: University at Buffalo
  - name: Lizhao Ge
    url: 
    orcid:
    affiliation: George Washington University
  - name: Jennifer Moore
    url: 
    orcid: 0000-0001-6628-6820
    affiliation: Washington University in St. Louis
  - name: Jennifer Moore
    url: 
    orcid: 0000-0001-6628-6820
    affiliation: Washington University in St. Louis
  - name: Jonathan Petters
    url: 
    orcid: 0000-0002-0853-5814
    affiliation: Virginia Tech
  - name: Wendy Kozlowski
    url: 
    orcid: 0000-0001-6539-3798
    affiliation: Cornell University
  - name: Cynthia Hudson Vitale
    url: 
    orcid: 0000-0001-5581-5678
    affiliation: Johns Hopkins University
categories: 
  - Data sharing
  - Data management
  - Scholarly communication
pub-info:
  reference: >-
    Lisa R Johnson, Alicia Hofelich Mohr, <strong><a href="https://joelherndon.info/">Joel Herndon</a></strong>, Shwana Taylor, Jake R. Carlson, Lizhao Ge, Jennifer Moore, Jonathan Petters, Wendy Kozlowski, and Cynthia Hudson Vitale, “Seek and you may (not) find: A multi-institutional analysis of where research data are shared,” <em>PLOS ONE</em> (2024), doi: <a href="https://doi.org/10.1371/journal.pone.0302426"><code>https://doi.org/10.5281/zenodo.8368204</code></a>
  links:
    - name: Final version
      url: https://doi.org/10.1371/journal.pone.0302426
      icon: fa-solid fa-scroll
    - name: Code
      url: https://doi.org/10.5281/zenodo.8368204
      icon: fa-brands fa-github
    - name: Data
      url: https://doi.org/10.5281/zenodo.8368204
      icon: fa-solid fa-table
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1371/journal.pone.0302426
      icon: ai ai-zotero
doi: 10.1371/journal.pone.0302426
---

## Abstract

Research data sharing has become an expected component of scientific research and scholarly publishing practice over the last few decades, due in part to requirements for federally funded research. As part of a larger effort to better understand the workflows and costs of public access to research data, this project conducted a high-level analysis of where academic research data is most frequently shared. To do this, we leveraged the DataCite and Crossref application programming interfaces (APIs) in search of Publisher field elements demonstrating which data repositories were utilized by researchers from six academic research institutions between 2012–2022. In addition, we also ran a preliminary analysis of the quality of the metadata associated with these published datasets, comparing the extent to which information was missing from metadata fields deemed important for public access to research data. Results show that the top 10 publishers accounted for 89.0% to 99.8% of the datasets connected with the institutions in our study. Known data repositories, including institutional data repositories hosted by those institutions, were initially lacking from our sample due to varying metadata standards and practices. We conclude that the metadata quality landscape for published research datasets is uneven; key information, such as author affiliation, is often incomplete or missing from source data repositories and aggregators. To enhance the findability, interoperability, accessibility, and reusability (FAIRness) of research data, we provide a set of concrete recommendations that repositories and data authors can take to improve scholarly metadata associated with shared datasets.

## Citation

<p class="buttons" style="text-align:center;">
<a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1177/08997640251348654">{{< iconify academicons:zotero >}}&emsp;Add to Zotero {{< iconify fa7-solid:square-arrow-up-right >}}</a>
</p>

```bibtex
@article{johnston2024correction,
  title={Correction: Seek and you may (not) find: A multi-institutional analysis of where research data are shared},
  author={Johnston, Lisa R and Hofelich Mohr, Alicia and Herndon, Joel and Taylor, Shawna and Carlson, Jake R and Ge, Lizhao and Moore, Jennifer and Petters, Jonathan and Kozlowski, Wendy and Hudson Vitale, Cynthia},
  journal={Plos one},
  volume={19},
  number={6},
  pages={e0306199},
  year={2024},
  publisher={Public Library of Science San Francisco, CA USA}
}
```